version: '3'
networks:
  backend_db_net:
    driver: bridge

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - backend_db_net
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  db:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: booklibrary
    networks:
      - backend_db_net
    healthcheck:
      test: ["CMD-SHELL", "mariadb -h localhost -u root -ppassword -e 'SELECT 1'"]
      interval: 10s
      timeout: 10s
      retries: 5
